[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 6

[[main]]
  identifier = "archive"
  name = "Changelog"
  url = "archive"
  weight = 5

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3

[[main]]
  parent = "gallery"
  name = "Photos"
  url = "gallery/photo"
  weight = 1

[[main]]
  parent = "gallery"
  name = "4yr Old's art"
  url = "gallery/4-yo-paintings"
  weight = 2

[[main]]
  parent = "gallery"
  name = "5yr Old's art"
  url = "gallery/5-yo-paintings"
  weight = 3

[[main]]
  identifier = "posts"
  name = "Blog"
  url = "posts"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Blog"
  url = "posts"
  weight = 1


#[[main]]
#  parent = "posts"
#  name = "zzo"
#  url = "posts/zzo"

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase"
#  weight = 6


[[main]]
  identifier = "talks"
  name = "Talks"
  url = "talks"
  weight = 2